version: "3.3"
services:
  server:
    container_name: exaltcoin_server
    image: xarang/exaltcoin:latest
    ports:
      - "8765:8765"
    volumes:
      - .:/app
      - ./exaltcoin_data:/exaltcoin_data
